# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TXLiteAVDemo_Professional' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Nama', '~> 7.2.0'
  pod 'TXLiteAVSDK_Professional', '~> 8.0.9643'

end

target 'TXReplaykitUpload_Professional' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TXReplaykitUpload_Professional

  pod 'TXLiteAVSDK_Professional', '~> 8.0.9643'

end
